# Uncomment the next line to define a global platform for your project
 platform :ios, '14.2'

target 'Chatterbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YourProjectName
  pod 'AWSMobileClient'
  pod 'AWSS3'
  pod 'AWSCore'

end
